import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SocketContextProvider } from "@/useSocket";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketContextProvider>
          <div className="max-w-[500px] mx-auto h-screen">{children}</div>
        </SocketContextProvider>
      </body>
    </html>
  );
}
